language: go

sudo: true

go:
    - 1.7
    - 1.8
    - 1.9
    - master

before_install:
    - ln -s $HOME/gopath/src/github.com/ShadowApex $HOME/gopath/src/github.com/shadowapex
    - git clone https://github.com/GodotNativeTools/godot_headers.git
    - sudo cp -r godot_headers/* /usr/local/include

install:
    - go get github.com/pinzolo/casee

script:
    - go generate
    - CGO_CXXFLAGS="-I/usr/local/include -std=c11" go build -x -v -buildmode=c-shared -o libgodot.so ./examples/pong/pong.go
