language: go

go:
    - 1.7
    - 1.8
    - 1.9

before_install:
    - ln -s $HOME/gopath/src/github.com/ShadowApex $HOME/gopath/src/github.com/shadowapex

install:
    - go get golang.org/x/tools/cmd/goimports

script:
    - go generate
    - go build -v -buildmode=c-shared -o libgodot.so examples/godot/DodgeTheCreeps/src/player.go
